apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: cxtp083xk-python 
  janus-idp.io/tekton: cxtp083xk-python
  backstage.io/kubernetes-id: cxtp083xk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cxtp083xk-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  