apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cxtp083xk-python
  janus-idp.io/tekton: cxtp083xk-python
  backstage.io/kubernetes-id: cxtp083xk-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cxtp083xk-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
